name: Windows Self-Hosted Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  WindowsSelfHostedBuild:
    name: Build Opus on Self-Hosted Windows Runner
    runs-on: [self-hosted, windows, x64]
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows/Lib/X64/Release",
            arch: x64,
            build_type: Release,
            shared: OFF
          }
        - {
            name: "Windows/Dll/X64/Release",
            arch: x64,
            build_type: Release,
            shared: ON
          }

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download models
        run: .\autogen.bat
        shell: cmd
      - name: Create build directory
        run: mkdir build
        shell: cmd
      - name: Configure CMake
        working-directory: ./build
        run: |
          cmake --version
          cmake .. -G "Visual Studio 17 2022" -A ${{ matrix.config.arch }} -DBUILD_SHARED_LIBS=${{ matrix.config.shared }} -DOPUS_BUILD_PROGRAMS=ON -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }}
        shell: cmd
      - name: Build
        working-directory: ./build
        run: cmake --build . -j 2 --config ${{ matrix.config.build_type }}
        shell: cmd
      - name: Test
        working-directory: ./build
        run: ctest -j 2 -C ${{ matrix.config.build_type }} --output-on-failure
        shell: cmd
      - name: Package
        working-directory: ./build
        run: cmake --build . --config ${{ matrix.config.build_type }} --target package
        shell: cmd
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: opus-${{ matrix.config.name }}
          path: build/*.zip
          if-no-files-found: ignore
